name: Build ModBootstrap
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Android NDK r27c
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: "r27c"

      - name: Compile libmodbootstrap.so
        env:
          ANDROID_NDK_ROOT: ${{ env.ANDROID_NDK_ROOT }}
        run: |
          chmod +x build-arm64.sh
          ./build-arm64.sh

      - name: Upload compiled so
        uses: actions/upload-artifact@v4
        with:
          name: compiled-libs
          path: dist/lib/arm64-v8a/libmodbootstrap.so
